// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCM.API.Data;

#nullable disable

namespace PCM.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260124081957_AddAdminTreasurerRefereeMember")]
    partial class AddAdminTreasurerRefereeMember
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "f190ffb7-883a-4707-9064-43ce6711d788",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "7327b048-6b69-435a-a9ca-fbbb7187c4ea",
                            Name = "Treasurer",
                            NormalizedName = "TREASURER"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "d8f33f44-63e8-491f-95c1-efb8ee00e30b",
                            Name = "Referee",
                            NormalizedName = "REFEREE"
                        },
                        new
                        {
                            Id = "4",
                            ConcurrencyStamp = "226c8c82-6b31-4bb3-8406-81fe67c34f5c",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-user-id-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "admin-concurrency-stamp-001",
                            Email = "admin@pcm.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@PCM.COM",
                            NormalizedUserName = "ADMIN@PCM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELDNqhJ0Z5xqR8nKCkX3f8fqDKpA1bF+2EHg5J7jqF9K3F8F9LvG3q4N5vR6yTkW9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ADMIN-SECURITY-STAMP-001",
                            TwoFactorEnabled = false,
                            UserName = "admin@pcm.com"
                        },
                        new
                        {
                            Id = "treasurer-user-id-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "treasurer-concurrency-stamp-001",
                            Email = "treasurer@pcm.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TREASURER@PCM.COM",
                            NormalizedUserName = "TREASURER@PCM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELDNqhJ0Z5xqR8nKCkX3f8fqDKpA1bF+2EHg5J7jqF9K3F8F9LvG3q4N5vR6yTkW9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "TREASURER-SECURITY-STAMP-001",
                            TwoFactorEnabled = false,
                            UserName = "treasurer@pcm.com"
                        },
                        new
                        {
                            Id = "referee-user-id-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "referee-concurrency-stamp-001",
                            Email = "referee@pcm.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "REFEREE@PCM.COM",
                            NormalizedUserName = "REFEREE@PCM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELDNqhJ0Z5xqR8nKCkX3f8fqDKpA1bF+2EHg5J7jqF9K3F8F9LvG3q4N5vR6yTkW9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "REFEREE-SECURITY-STAMP-001",
                            TwoFactorEnabled = false,
                            UserName = "referee@pcm.com"
                        },
                        new
                        {
                            Id = "member-user-id-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "member-concurrency-stamp-001",
                            Email = "member1@pcm.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER1@PCM.COM",
                            NormalizedUserName = "MEMBER1@PCM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELDNqhJ0Z5xqR8nKCkX3f8fqDKpA1bF+2EHg5J7jqF9K3F8F9LvG3q4N5vR6yTkW9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "MEMBER-SECURITY-STAMP-001",
                            TwoFactorEnabled = false,
                            UserName = "member1@pcm.com"
                        },
                        new
                        {
                            Id = "member-user-id-002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "member-concurrency-stamp-002",
                            Email = "member2@pcm.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER2@PCM.COM",
                            NormalizedUserName = "MEMBER2@PCM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELDNqhJ0Z5xqR8nKCkX3f8fqDKpA1bF+2EHg5J7jqF9K3F8F9LvG3q4N5vR6yTkW9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "MEMBER-SECURITY-STAMP-002",
                            TwoFactorEnabled = false,
                            UserName = "member2@pcm.com"
                        },
                        new
                        {
                            Id = "member-user-id-003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "member-concurrency-stamp-003",
                            Email = "member3@pcm.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER3@PCM.COM",
                            NormalizedUserName = "MEMBER3@PCM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELDNqhJ0Z5xqR8nKCkX3f8fqDKpA1bF+2EHg5J7jqF9K3F8F9LvG3q4N5vR6yTkW9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "MEMBER-SECURITY-STAMP-003",
                            TwoFactorEnabled = false,
                            UserName = "member3@pcm.com"
                        },
                        new
                        {
                            Id = "member-user-id-004",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "member-concurrency-stamp-004",
                            Email = "member4@pcm.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER4@PCM.COM",
                            NormalizedUserName = "MEMBER4@PCM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELDNqhJ0Z5xqR8nKCkX3f8fqDKpA1bF+2EHg5J7jqF9K3F8F9LvG3q4N5vR6yTkW9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "MEMBER-SECURITY-STAMP-004",
                            TwoFactorEnabled = false,
                            UserName = "member4@pcm.com"
                        },
                        new
                        {
                            Id = "member-user-id-005",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "member-concurrency-stamp-005",
                            Email = "member5@pcm.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER5@PCM.COM",
                            NormalizedUserName = "MEMBER5@PCM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELDNqhJ0Z5xqR8nKCkX3f8fqDKpA1bF+2EHg5J7jqF9K3F8F9LvG3q4N5vR6yTkW9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "MEMBER-SECURITY-STAMP-005",
                            TwoFactorEnabled = false,
                            UserName = "member5@pcm.com"
                        },
                        new
                        {
                            Id = "member-user-id-006",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "member-concurrency-stamp-006",
                            Email = "member6@pcm.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER6@PCM.COM",
                            NormalizedUserName = "MEMBER6@PCM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELDNqhJ0Z5xqR8nKCkX3f8fqDKpA1bF+2EHg5J7jqF9K3F8F9LvG3q4N5vR6yTkW9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "MEMBER-SECURITY-STAMP-006",
                            TwoFactorEnabled = false,
                            UserName = "member6@pcm.com"
                        },
                        new
                        {
                            Id = "member-user-id-007",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "member-concurrency-stamp-007",
                            Email = "member7@pcm.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER7@PCM.COM",
                            NormalizedUserName = "MEMBER7@PCM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELDNqhJ0Z5xqR8nKCkX3f8fqDKpA1bF+2EHg5J7jqF9K3F8F9LvG3q4N5vR6yTkW9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "MEMBER-SECURITY-STAMP-007",
                            TwoFactorEnabled = false,
                            UserName = "member7@pcm.com"
                        },
                        new
                        {
                            Id = "member-user-id-008",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "member-concurrency-stamp-008",
                            Email = "member8@pcm.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER8@PCM.COM",
                            NormalizedUserName = "MEMBER8@PCM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELDNqhJ0Z5xqR8nKCkX3f8fqDKpA1bF+2EHg5J7jqF9K3F8F9LvG3q4N5vR6yTkW9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "MEMBER-SECURITY-STAMP-008",
                            TwoFactorEnabled = false,
                            UserName = "member8@pcm.com"
                        },
                        new
                        {
                            Id = "member-user-id-009",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "member-concurrency-stamp-009",
                            Email = "member9@pcm.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER9@PCM.COM",
                            NormalizedUserName = "MEMBER9@PCM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELDNqhJ0Z5xqR8nKCkX3f8fqDKpA1bF+2EHg5J7jqF9K3F8F9LvG3q4N5vR6yTkW9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "MEMBER-SECURITY-STAMP-009",
                            TwoFactorEnabled = false,
                            UserName = "member9@pcm.com"
                        },
                        new
                        {
                            Id = "member-user-id-010",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "member-concurrency-stamp-010",
                            Email = "member10@pcm.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER10@PCM.COM",
                            NormalizedUserName = "MEMBER10@PCM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELDNqhJ0Z5xqR8nKCkX3f8fqDKpA1bF+2EHg5J7jqF9K3F8F9LvG3q4N5vR6yTkW9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "MEMBER-SECURITY-STAMP-010",
                            TwoFactorEnabled = false,
                            UserName = "member10@pcm.com"
                        },
                        new
                        {
                            Id = "member-user-id-011",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "member-concurrency-stamp-011",
                            Email = "member11@pcm.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER11@PCM.COM",
                            NormalizedUserName = "MEMBER11@PCM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELDNqhJ0Z5xqR8nKCkX3f8fqDKpA1bF+2EHg5J7jqF9K3F8F9LvG3q4N5vR6yTkW9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "MEMBER-SECURITY-STAMP-011",
                            TwoFactorEnabled = false,
                            UserName = "member11@pcm.com"
                        },
                        new
                        {
                            Id = "member-user-id-012",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "member-concurrency-stamp-012",
                            Email = "member12@pcm.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER12@PCM.COM",
                            NormalizedUserName = "MEMBER12@PCM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELDNqhJ0Z5xqR8nKCkX3f8fqDKpA1bF+2EHg5J7jqF9K3F8F9LvG3q4N5vR6yTkW9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "MEMBER-SECURITY-STAMP-012",
                            TwoFactorEnabled = false,
                            UserName = "member12@pcm.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin-user-id-001",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "treasurer-user-id-001",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "referee-user-id-001",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "member-user-id-001",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "member-user-id-002",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "member-user-id-003",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "member-user-id-004",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "member-user-id-005",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "member-user-id-006",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "member-user-id-007",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "member-user-id-008",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "member-user-id-009",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "member-user-id-010",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "member-user-id-011",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "member-user-id-012",
                            RoleId = "4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PCM.API.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("MemberId");

                    b.ToTable("002_Bookings");
                });

            modelBuilder.Entity("PCM.API.Models.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Config_TargetWins")
                        .HasColumnType("int");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentScore_TeamA")
                        .HasColumnType("int");

                    b.Property<int>("CurrentScore_TeamB")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EntryFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GameMode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrizePool")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("002_Challenges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Config_TargetWins = 5,
                            CreatedById = 1,
                            CreatedDate = new DateTime(2026, 1, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentScore_TeamA = 2,
                            CurrentScore_TeamB = 1,
                            Description = "Giải đấu chia 2 phe A-B, đánh chạm mốc 5 trận thắng.",
                            EndDate = new DateTime(2026, 1, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            EntryFee = 50000m,
                            GameMode = 1,
                            PrizePool = 500000m,
                            StartDate = new DateTime(2026, 1, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            Title = "Giải Mini-game Team Battle tháng 1/2026",
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedById = 1,
                            CreatedDate = new DateTime(2026, 1, 23, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentScore_TeamA = 0,
                            CurrentScore_TeamB = 0,
                            Description = "Kèo vui vẻ, thua mời nước!",
                            EntryFee = 0m,
                            GameMode = 0,
                            PrizePool = 0m,
                            Status = 1,
                            Title = "Kèo thách đấu: An vs Cường",
                            Type = 1
                        });
                });

            modelBuilder.Entity("PCM.API.Models.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("002_Courts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sân chính - có đèn chiếu sáng",
                            IsActive = true,
                            Name = "Sân 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sân phụ - có quạt mát",
                            IsActive = true,
                            Name = "Sân 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đang bảo trì",
                            IsActive = false,
                            Name = "Sân 3"
                        });
                });

            modelBuilder.Entity("PCM.API.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRanked")
                        .HasColumnType("bit");

                    b.Property<int>("MatchFormat")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Team1_Player1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Team1_Player2Id")
                        .HasColumnType("int");

                    b.Property<int>("Team2_Player1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Team2_Player2Id")
                        .HasColumnType("int");

                    b.Property<int>("WinningSide")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("Team1_Player1Id");

                    b.HasIndex("Team1_Player2Id");

                    b.HasIndex("Team2_Player1Id");

                    b.HasIndex("Team2_Player2Id");

                    b.ToTable("002_Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChallengeId = 1,
                            CreatedDate = new DateTime(2026, 1, 23, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 1, 23, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRanked = true,
                            MatchFormat = 1,
                            Team1_Player1Id = 4,
                            Team2_Player1Id = 9,
                            WinningSide = 1
                        },
                        new
                        {
                            Id = 2,
                            ChallengeId = 1,
                            CreatedDate = new DateTime(2026, 1, 23, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 1, 23, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRanked = true,
                            MatchFormat = 1,
                            Team1_Player1Id = 5,
                            Team2_Player1Id = 10,
                            WinningSide = 1
                        },
                        new
                        {
                            Id = 3,
                            ChallengeId = 1,
                            CreatedDate = new DateTime(2026, 1, 24, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 1, 24, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRanked = true,
                            MatchFormat = 2,
                            Team1_Player1Id = 6,
                            Team1_Player2Id = 7,
                            Team2_Player1Id = 11,
                            Team2_Player2Id = 12,
                            WinningSide = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 1, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRanked = true,
                            MatchFormat = 1,
                            Team1_Player1Id = 4,
                            Team2_Player1Id = 6,
                            WinningSide = 1
                        });
                });

            modelBuilder.Entity("PCM.API.Models.MatchScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsFinalSet")
                        .HasColumnType("bit");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<int>("Team1Score")
                        .HasColumnType("int");

                    b.Property<int>("Team2Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("002_MatchScores");
                });

            modelBuilder.Entity("PCM.API.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("RankLevel")
                        .HasColumnType("float");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WinMatches")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("002_Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@pcm.com",
                            FullName = "Admin CLB",
                            IsActive = true,
                            JoinDate = new DateTime(2021, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0901234500",
                            RankLevel = 5.0,
                            TotalMatches = 100,
                            UserId = "admin-user-id-001",
                            WinMatches = 80
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1988, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "treasurer@pcm.com",
                            FullName = "Thủ quỹ CLB",
                            IsActive = true,
                            JoinDate = new DateTime(2023, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0901234501",
                            RankLevel = 4.0,
                            TotalMatches = 50,
                            UserId = "treasurer-user-id-001",
                            WinMatches = 35
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "referee@pcm.com",
                            FullName = "Trọng tài CLB",
                            IsActive = true,
                            JoinDate = new DateTime(2024, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "0901234502",
                            RankLevel = 4.5,
                            TotalMatches = 30,
                            UserId = "referee-user-id-001",
                            WinMatches = 20
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 12, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member1@pcm.com",
                            FullName = "Nguyễn Văn An",
                            IsActive = true,
                            JoinDate = new DateTime(2025, 12, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "09012345600",
                            RankLevel = 4.5,
                            TotalMatches = 20,
                            UserId = "member-user-id-001",
                            WinMatches = 15
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 11, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1991, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member2@pcm.com",
                            FullName = "Trần Thị Bình",
                            IsActive = true,
                            JoinDate = new DateTime(2025, 11, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "09012345601",
                            RankLevel = 4.2000000000000002,
                            TotalMatches = 19,
                            UserId = "member-user-id-002",
                            WinMatches = 14
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 10, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1992, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member3@pcm.com",
                            FullName = "Lê Văn Cường",
                            IsActive = true,
                            JoinDate = new DateTime(2025, 10, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "09012345602",
                            RankLevel = 4.0,
                            TotalMatches = 18,
                            UserId = "member-user-id-003",
                            WinMatches = 13
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 9, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1993, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member4@pcm.com",
                            FullName = "Phạm Thị Dung",
                            IsActive = true,
                            JoinDate = new DateTime(2025, 9, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "09012345603",
                            RankLevel = 3.7999999999999998,
                            TotalMatches = 17,
                            UserId = "member-user-id-004",
                            WinMatches = 12
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 8, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1994, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member5@pcm.com",
                            FullName = "Hoàng Văn Em",
                            IsActive = true,
                            JoinDate = new DateTime(2025, 8, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "09012345604",
                            RankLevel = 3.6000000000000001,
                            TotalMatches = 16,
                            UserId = "member-user-id-005",
                            WinMatches = 11
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 7, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1995, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member6@pcm.com",
                            FullName = "Vũ Thị Phương",
                            IsActive = true,
                            JoinDate = new DateTime(2025, 7, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "09012345605",
                            RankLevel = 3.5,
                            TotalMatches = 15,
                            UserId = "member-user-id-006",
                            WinMatches = 10
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 6, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1996, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member7@pcm.com",
                            FullName = "Đặng Văn Giang",
                            IsActive = true,
                            JoinDate = new DateTime(2025, 6, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "09012345606",
                            RankLevel = 3.3999999999999999,
                            TotalMatches = 14,
                            UserId = "member-user-id-007",
                            WinMatches = 9
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 5, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1997, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member8@pcm.com",
                            FullName = "Bùi Thị Hoa",
                            IsActive = true,
                            JoinDate = new DateTime(2025, 5, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "09012345607",
                            RankLevel = 3.2000000000000002,
                            TotalMatches = 13,
                            UserId = "member-user-id-008",
                            WinMatches = 8
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 4, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1998, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member9@pcm.com",
                            FullName = "Ngô Văn Khải",
                            IsActive = true,
                            JoinDate = new DateTime(2025, 4, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "09012345608",
                            RankLevel = 3.0,
                            TotalMatches = 12,
                            UserId = "member-user-id-009",
                            WinMatches = 7
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 3, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1999, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member10@pcm.com",
                            FullName = "Lý Thị Lan",
                            IsActive = true,
                            JoinDate = new DateTime(2025, 3, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "09012345609",
                            RankLevel = 2.7999999999999998,
                            TotalMatches = 11,
                            UserId = "member-user-id-010",
                            WinMatches = 6
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2025, 2, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member11@pcm.com",
                            FullName = "Đinh Văn Minh",
                            IsActive = true,
                            JoinDate = new DateTime(2025, 2, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "09012345610",
                            RankLevel = 2.5,
                            TotalMatches = 10,
                            UserId = "member-user-id-011",
                            WinMatches = 5
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2025, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1991, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member12@pcm.com",
                            FullName = "Trương Thị Ngọc",
                            IsActive = true,
                            JoinDate = new DateTime(2025, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "09012345611",
                            RankLevel = 2.0,
                            TotalMatches = 9,
                            UserId = "member-user-id-012",
                            WinMatches = 4
                        });
                });

            modelBuilder.Entity("PCM.API.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("002_News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "CLB tổ chức giải đấu Team Battle với Entry Fee 50.000đ/người. Thời gian: 25-26/01/2026. Đăng ký ngay!",
                            CreatedDate = new DateTime(2026, 1, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPinned = true,
                            Title = "🏆 Giải đấu Mini-game Team Battle tháng 1/2026"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Các thành viên vui lòng đóng quỹ tháng 1/2026 (100.000đ) trước ngày 31/01. Liên hệ Thủ quỹ để chuyển khoản.",
                            CreatedDate = new DateTime(2026, 1, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPinned = true,
                            Title = "📢 Thông báo đóng quỹ tháng 1/2026"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Chúc mừng An, Bình, Cường, Dung, Em đã đạt Top 5 Rank DUPR cao nhất tháng 12/2025!",
                            CreatedDate = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPinned = false,
                            Title = "🎉 Vinh danh Top 5 cao thủ tháng 12/2025"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Sân 3 sẽ tạm đóng để sửa chữa mặt sân và thay đèn. Các bạn vui lòng đặt sân 1 hoặc sân 2.",
                            CreatedDate = new DateTime(2026, 1, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPinned = false,
                            Title = "🔧 Bảo trì Sân 3 từ 20-30/01/2026"
                        });
                });

            modelBuilder.Entity("PCM.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("002_Notifications");
                });

            modelBuilder.Entity("PCM.API.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<decimal>("EntryFeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EntryFeePaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("MemberId");

                    b.ToTable("002_Participants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChallengeId = 1,
                            EntryFeeAmount = 50000m,
                            EntryFeePaid = true,
                            JoinedDate = new DateTime(2026, 1, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 4,
                            Status = 2,
                            Team = 1
                        },
                        new
                        {
                            Id = 2,
                            ChallengeId = 1,
                            EntryFeeAmount = 50000m,
                            EntryFeePaid = true,
                            JoinedDate = new DateTime(2026, 1, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 5,
                            Status = 2,
                            Team = 1
                        },
                        new
                        {
                            Id = 3,
                            ChallengeId = 1,
                            EntryFeeAmount = 50000m,
                            EntryFeePaid = true,
                            JoinedDate = new DateTime(2026, 1, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 6,
                            Status = 2,
                            Team = 1
                        },
                        new
                        {
                            Id = 4,
                            ChallengeId = 1,
                            EntryFeeAmount = 50000m,
                            EntryFeePaid = true,
                            JoinedDate = new DateTime(2026, 1, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 7,
                            Status = 2,
                            Team = 1
                        },
                        new
                        {
                            Id = 5,
                            ChallengeId = 1,
                            EntryFeeAmount = 50000m,
                            EntryFeePaid = true,
                            JoinedDate = new DateTime(2026, 1, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 8,
                            Status = 2,
                            Team = 1
                        },
                        new
                        {
                            Id = 6,
                            ChallengeId = 1,
                            EntryFeeAmount = 50000m,
                            EntryFeePaid = true,
                            JoinedDate = new DateTime(2026, 1, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 9,
                            Status = 2,
                            Team = 2
                        },
                        new
                        {
                            Id = 7,
                            ChallengeId = 1,
                            EntryFeeAmount = 50000m,
                            EntryFeePaid = true,
                            JoinedDate = new DateTime(2026, 1, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 10,
                            Status = 2,
                            Team = 2
                        },
                        new
                        {
                            Id = 8,
                            ChallengeId = 1,
                            EntryFeeAmount = 50000m,
                            EntryFeePaid = true,
                            JoinedDate = new DateTime(2026, 1, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 11,
                            Status = 2,
                            Team = 2
                        },
                        new
                        {
                            Id = 9,
                            ChallengeId = 1,
                            EntryFeeAmount = 50000m,
                            EntryFeePaid = true,
                            JoinedDate = new DateTime(2026, 1, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 12,
                            Status = 2,
                            Team = 2
                        },
                        new
                        {
                            Id = 10,
                            ChallengeId = 1,
                            EntryFeeAmount = 50000m,
                            EntryFeePaid = true,
                            JoinedDate = new DateTime(2026, 1, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 13,
                            Status = 2,
                            Team = 2
                        });
                });

            modelBuilder.Entity("PCM.API.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedById");

                    b.ToTable("002_Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1000000m,
                            CategoryId = 2,
                            CreatedById = 1,
                            CreatedDate = new DateTime(2025, 12, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 12, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thu quỹ tháng 12/2025"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 500000m,
                            CategoryId = 1,
                            CreatedById = 1,
                            CreatedDate = new DateTime(2025, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 12, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thu tiền sân tuần 1"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 300000m,
                            CategoryId = 4,
                            CreatedById = 1,
                            CreatedDate = new DateTime(2026, 1, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 1, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tài trợ từ shop bóng"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 200000m,
                            CategoryId = 5,
                            CreatedById = 1,
                            CreatedDate = new DateTime(2025, 12, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 12, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mua nước cho hội viên"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 150000m,
                            CategoryId = 7,
                            CreatedById = 1,
                            CreatedDate = new DateTime(2026, 1, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 1, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mua bóng mới"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 100000m,
                            CategoryId = 8,
                            CreatedById = 1,
                            CreatedDate = new DateTime(2026, 1, 9, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 1, 9, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sửa vợt CLB"
                        });
                });

            modelBuilder.Entity("PCM.API.Models.TransactionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("002_TransactionCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tiền sân",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Quỹ tháng",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tiền thưởng từ giải",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tài trợ",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nước",
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Phạt",
                            Type = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mua bóng",
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sửa chữa",
                            Type = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PCM.API.Models.Booking", b =>
                {
                    b.HasOne("PCM.API.Models.Court", "Court")
                        .WithMany("Bookings")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCM.API.Models.Member", "Member")
                        .WithMany("Bookings")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PCM.API.Models.Challenge", b =>
                {
                    b.HasOne("PCM.API.Models.Member", "CreatedBy")
                        .WithMany("CreatedChallenges")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("PCM.API.Models.Match", b =>
                {
                    b.HasOne("PCM.API.Models.Challenge", "Challenge")
                        .WithMany("Matches")
                        .HasForeignKey("ChallengeId");

                    b.HasOne("PCM.API.Models.Member", "Team1_Player1")
                        .WithMany()
                        .HasForeignKey("Team1_Player1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PCM.API.Models.Member", "Team1_Player2")
                        .WithMany()
                        .HasForeignKey("Team1_Player2Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PCM.API.Models.Member", "Team2_Player1")
                        .WithMany()
                        .HasForeignKey("Team2_Player1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PCM.API.Models.Member", "Team2_Player2")
                        .WithMany()
                        .HasForeignKey("Team2_Player2Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Challenge");

                    b.Navigation("Team1_Player1");

                    b.Navigation("Team1_Player2");

                    b.Navigation("Team2_Player1");

                    b.Navigation("Team2_Player2");
                });

            modelBuilder.Entity("PCM.API.Models.MatchScore", b =>
                {
                    b.HasOne("PCM.API.Models.Match", "Match")
                        .WithMany("Scores")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("PCM.API.Models.Notification", b =>
                {
                    b.HasOne("PCM.API.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PCM.API.Models.Participant", b =>
                {
                    b.HasOne("PCM.API.Models.Challenge", "Challenge")
                        .WithMany("Participants")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCM.API.Models.Member", "Member")
                        .WithMany("Participations")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PCM.API.Models.Transaction", b =>
                {
                    b.HasOne("PCM.API.Models.TransactionCategory", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCM.API.Models.Member", "CreatedBy")
                        .WithMany("Transactions")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("PCM.API.Models.Challenge", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("PCM.API.Models.Court", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("PCM.API.Models.Match", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("PCM.API.Models.Member", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CreatedChallenges");

                    b.Navigation("Participations");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PCM.API.Models.TransactionCategory", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
